### ISSUE TITLE
Module 'ScanditBarcodeScanner' not found iOS

### ISSUE THREAD

**Issue by kristotruu** [Scandit/barcodescanner-sdk-react-native#102]
iOS SDK version 5.9.2
React Native 0.57.5
xcode 9.2

Followed all instructions:
https://docs.scandit.com/stable/react_native/react-native-integrate.html

After trying to build in xcode the application has been received build failed with exception" Module 'ScanditBarcodeScanner' not found" in SCNScandiModule.m file.

![image](https://user-images.githubusercontent.com/16351470/50549394-d4ebd900-0c64-11e9-9022-1ec0c8a3a725.png)

![image](https://user-images.githubusercontent.com/16351470/50549398-e7661280-0c64-11e9-8cfa-25fa4962c447.png)

How to include the module?

**Comment by kristotruu** [comment]
Downloading latest SDK version solves the problem

**Comment by BaloMueller** [comment]
I have the same problem. I downloaded the latest version 5.10.1.
