### ISSUE TITLE
scanner.stopScanning() freeze app on Samsung phones

### ISSUE THREAD

**Issue by Racistpanda** [Scandit/barcodescanner-sdk-react-native#130]
Hello,
I'm able to reproduce a freeze on lower tier samsung phones (tested with samsung galaxy s3 with android 4.4 and samsung galaxy j4 with android 8.0) on your Extended sample.

Videos here: https://youtu.be/f7D8-NGreIk https://youtu.be/XTlRhYGt1EM
Test code im using here: https://github.com/Racistpanda/scandit-error-2

Kind of hard to see, but im trying to switch tabs as what appears to be the moment it tries to analyze the scan? Doesn't happen all the time, sometimes you have to repeat for more than 30 tries.
Anyway, same issue has been happening in our app. When onScan method fires we hit session.stopScanning and go back on navigation and some times it leads to a freeze (seems to be only happening on Samsung phones!).

Android debug console doesn't show anything.

**Comment by TomekJurkowski** [comment]
Hello,

thanks for raising this issue, we will try to reproduce the freeze that you are experiencing. Will get back to you, as soon as we have a fix !

Cheers

**Comment by TomekJurkowski** [comment]
Hello @Racistpanda ,
we have just updated `master` and `release-5.11` branches with a fix for your issue.
Many Thanks,
Tomek

**Comment by Racistpanda** [comment]
Yay! Thank you! Can you push this update to npm too?

**Comment by TomekJurkowski** [comment]
Hey, we have a release of a new 5.11 version of our library planned for early next week (not just for RN, but also other platforms & frameworks) and that's when a new version will be uploaded to npm. I hope that is okay for you.

Cheers!
