### ISSUE TITLE
':react-native-scandit:compileReleaseKotlin' Compilation error

### ISSUE THREAD

**Issue by JorgeCeja** [Scandit/barcodescanner-sdk-react-native#14]
My setup is:
"react-native": "0.48.4"
"react-native-scandit": "https://github.com/Scandit/barcodescanner-sdk-react-native.git"

**Here is the error I got:**

node_modules/react-native-scandit/android/src/main/java/com/scandit/reactnative/BarcodePicker.kt: (59, 54): Unresolved reference: `setTorchButtonMarginsSize`
:react-native-scandit:compileReleaseKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-scandit:compileReleaseKotlin'.
> Compilation error. See log for more details

**Temporary Solution:**
What I did was to simply remove line 59 in which the `Unresolved reference` occurred.

**Similar to pull request #13**

**Comment by moritz-scandit** [comment]
#13 was merged and fixed this issue, so this is not relevant anymore as far as I can see.

**Comment by JorgeCeja** [comment]
Thanks! @moritz-scandit
