### ISSUE TITLE
Build failed with an exception. android

### ISSUE THREAD

**Issue by dontuse** [Scandit/barcodescanner-sdk-react-native#144]
> Task :scandit-react-native:compileDebugKotlin FAILED
e: /Users/andrey/dev/karicameraexample/node_modules/scandit-react-native/android/src/main/java/com/scandit/reactnative/BarcodePicker.kt: (22, 122): Unresolved reference: WarningsListener
e: /Users/andrey/dev/karicameraexample/node_modules/scandit-react-native/android/src/main/java/com/scandit/reactnative/BarcodePicker.kt: (93, 17): Unresolved reference: addWarningsListener
e: /Users/andrey/dev/karicameraexample/node_modules/scandit-react-native/android/src/main/java/com/scandit/reactnative/BarcodePicker.kt: (177, 5): 'onWarnings' overrides nothing

packages.json :

{
  "name": "karicameraexample",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "run": "node node_modules/react-native/local-cli/cli.js run-android",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.8.3",
    "react-native": "0.59.0",
    "react-native-camera-kit": "^7.3.4",
    "react-navigation": "^2.18.3",
    "scandit-react-native": "^5.11.0"
  },
  "devDependencies": {
    "@babel/core": "^7.3.4",
    "@babel/runtime": "^7.3.4",
    "babel-jest": "^24.5.0",
    "jest": "^24.5.0",
    "metro-react-native-babel-preset": "^0.53.0",
    "react-test-renderer": "16.8.3"
  },
  "jest": {
    "preset": "react-native"
  }
}

build.gradle

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        flatDir {
            dirs "$rootDir/libs"
        }
        mavenLocal()
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }

    }
}

**Comment by dontuse** [comment]
also i have project with 0.58.6 react-native, i solve compile kotlin problem with this git+https://github.com/temideoye/barcodescanner-sdk-react-native.git

**Comment by moritzhartmeier** [comment]
Hi @dontuse 

The unresolved references that you see are part of the 5.11 release, I assume that your native library is still 5.10 and that is why you don't have the references. The solution is to simply download the newest 5.11 android sdk from your account at scandit.com and copy its aar over the one you currently use.

If you are using a pre-0.59 version of react native then you will have to also use an older version of our plugin, it is probably best to update to a newer react native version though.

Let us know if everything worked.
