### ISSUE TITLE
setMatrixScanHighlightingColor Function Not Working

### ISSUE THREAD

**Issue by a1224** [Scandit/barcodescanner-sdk-react-native#165]
I am having some trouble calling the function setMatrixScanHighlightingColor().

I am calling it like this, in componentDidMount():

`this.scanner.setMatrixScanHighlightingColor(ScanOverlay.MatrixScanState.MATRIX_SCAN_STATE_RECOGNIZED, '#F00');`,

where `this.scanner` is a ref to a BarcodePicker.

The result is this error:
`Argument 1 (NSInteger) of UIManager.dispatchViewManagerCommand must not be null`

**Comment by petradonka** [comment]
Thanks for reaching out, we'll take a look at the issue and get back to you.

**Comment by petradonka** [comment]
Hey @a1224,

We found and fixed the issue you reported and it'll be part of the 5.12 release that's coming up.
