### ISSUE TITLE
Upgrade to 5.11.3 - scandit-react-native:compileDebugKotlin FAILED

### ISSUE THREAD

**Issue by Ronen-dev** [Scandit/barcodescanner-sdk-react-native#167]
After upgrading `scandit-react-native` from `5.10.1` to `5.11.3`, I got the following error while building :

```
> Task :scandit-react-native:compileDebugKotlin FAILED
e: <path_to_project>/node_modules/scandit-react-native/android/src/main/java/com/scandit/reactnative/BarcodePicker.kt: (30, 31): Unresolved reference: WarningsListener
e: <path_to_project>/node_modules/scandit-react-native/android/src/main/java/com/scandit/reactnative/BarcodePicker.kt: (118, 17): Unresolved reference: addWarningsListener
e: <path_to_project>/node_modules/scandit-react-native/android/src/main/java/com/scandit/reactnative/BarcodePicker.kt: (220, 5): 'onWarnings' overrides nothing
```

It seems to be related to #14 and #109, but both have fix which have been released since.

Current setup is :
- **react-native**: `0.58.4`
- **scandit-react-native** : from `5.10.1` to `5.11.3`

**Comment by moritzhartmeier** [comment]
Hi @Ronen-dev 

It looks like you are using an outdated version of the native library (5.10.1 probably) which has to be manually moved in during installation, the same is the case for when you update. So you have to download the 5.11.3 native android sdk and copy it in as written in the integration instructions (https://docs.scandit.com/stable/react_native/react-native-integrate.html).

**Comment by Ronen-dev** [comment]
The native library was indeed the old one (`5.10.1`), thanks @moritzhartmeier !

**Comment by Boris-c** [comment]
Hi @moritzhartmeier and @Ronen-dev 

Where did you find the 5.11.3 .aar file??

The download section on my scandit account shows 6.0.0, then 5.10.1 and below.

**Comment by moritzhartmeier** [comment]
Hy @Boris-c 

I just checked an account and i can see all 5.11 releases right between 6.0 and 5.10. If you aren't seeing them please contact support@scandit.com for us to check your account.

**Comment by Boris-c** [comment]
Hi @moritzhartmeier,

I definitely can’t see any 5.11 file in the download section. I sent a screenshot to support@scandit.com.

I’ve been in touch with your support for 4 days and still don’t have access to the supposedly easy to find 5.11 file.

I’d greatly appreciate being provided with a simple link to the file, for instance, because spending 4 days sending 5 emails and writing comments on GitHub issues for a mere download is starting to make me nervous.

Thanks in advance.

**Comment by moritzhartmeier** [comment]
Hi @Boris-c ,

My apologies, i've asked support to have a look right away.

**Comment by Boris-c** [comment]
Hi @moritzhartmeier ,

Thanks
