### ISSUE TITLE
Build failed with an exception. [Android]

### ISSUE THREAD

**Issue by nitish1099** [Scandit/barcodescanner-sdk-react-native#168]
**React Native Info:**
System:
    OS: macOS 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 20.31 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.12.0 - ~/.nvm/versions/node/v10.12.0/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.12.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 27.0.3, 28.0.2, 28.0.3
      System Images: android-27 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.0 => 0.60.0 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
    react-native-rename: 2.3.2

**Error Log**:

`/Users/nitishanand/barcodeExample/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:17: error: ';' expected
import com.scandit.reactnative.ScanditPackage();
                                             ^
/Users/nitishanand/barcodeExample/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:51: error: ')' expected
      new ScanditPackage()()
                          ^
/Users/nitishanand/barcodeExample/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:51: error: ';' expected
      new ScanditPackage()()
                           ^
/Users/nitishanand/barcodeExample/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:52: error: illegal start of expression
    ));
    ^
/Users/nitishanand/barcodeExample/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:52: error: ';' expected
    ));
     ^
5 errors`

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by tuantvk** [comment]
@nitish1099 
Error when you link **scandit-react-native**.
in file **MainApplication.java**: _app_name/android/app/src/main/java/com/app_name/MainApplication.java_

- change
 **import com.scandit.reactnative.ScanditPackage();**
to
**import com.scandit.reactnative.ScanditPackage;**

and

- _in List < ReactPackage >_
change 
**new ScanditPackage()()**
to:
**new ScanditPackage()**

and rebuild it

**Comment by nitish1099** [comment]
> * in List < ReactPackage >

Where is this directory?

**Comment by tuantvk** [comment]
@nitish1099, you can search new **ScanditPackage()()** in _MainApplication.java_

**Comment by TomekJurkowski** [comment]
Hey @nitish1099, I am closing this issue, as it seems to me @tuantvk gave you a good tip how to resolve your problem. However, if you are still facing the compilation failure, please let us know (sending a small sample that we could use to recreate your issue on our side would be helpful in that case).
