### ISSUE TITLE
Module 'ScanditBarcodeScanner' not found in iOS 

### ISSUE THREAD

**Issue by knalliyappan** [Scandit/barcodescanner-sdk-react-native#172]
Downloaded the source code from the github

Add the License Key Details to the sample project.

We got the "Module 'ScanditBarcodeScanner' not found" error in iOS .

Attached the screen shot for your reference
![Screen Shot 2019-07-24 at 12 46 27 PM](https://user-images.githubusercontent.com/48433441/61773111-790bbc00-ae11-11e9-8f35-601e80189ff5.png)

**Comment by petradonka** [comment]
Hey @knalliyappan,

Did you add the iOS framework to the project, as described on https://docs.scandit.com/stable/react_native/react-native-examples.html under "Add iOS dependencies"?

**Comment by knalliyappan** [comment]
Added the below frameworks:
ScanditBarcodeCapture.framework
ScanditCaptureCore.framework
ScanditLabelCapture.framework

Attached the screen shot for your reference
![Screenshot-Screen-Shot-2019-07-24-at-1-03-12-PM-2019-07-24-13-07-33](https://user-images.githubusercontent.com/48433441/61774157-e3bdf700-ae13-11e9-89fc-0abff5292681.png)

**Comment by petradonka** [comment]
You seem to have downloaded the 6.x version. React Native is only available for 5.x, please try downloading and adding the framework with the same version that you're using for the plugin.

**Comment by knalliyappan** [comment]
Changed to 5.x and added the ScanditBarcodeScanner.framework still have the same issue.

**Comment by petradonka** [comment]
I just tried to reproduce this by following our [steps to run the sample](https://docs.scandit.com/stable/react_native/react-native-examples.html), using the 5.11.4 framework downloaded from our dashboard and everything built fine, I did not get any errors.

I'd suggest to try again from scratch, including (re)downloading the RN plugin and the iOS framework, _closely_ following the steps outlined in our docs.

If you're still running into issues, please contact support@scandit.com so our support team can help you resolve the issue!
