### ISSUE TITLE
Could not resolve project :scandit-react-native (Android)

### ISSUE THREAD

**Issue by brayanL** [Scandit/barcodescanner-sdk-react-native#179]
Versions:
**scandit-react-native:** 5.11.4
**react-native:** 0.58.4

I have the following error with Gradle on Android:
```
ERROR: Unable to resolve dependency for ':app@profile/compileClasspath': Could not resolve project :scandit-react-native.
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@profileUnitTest/compileClasspath': Could not resolve project :scandit-react-native.
Show Details
Affected Modules: app
```
I followed these instructions: [https://docs.scandit.com/stable/react_native/react-native-integrate.html](url)

I have also added the file `ScanditBarcodeScanner.aar` to libs directory, I don't know why scan-react-native project cannot be found.

Any solutions or ideas?

**Comment by petradonka** [comment]
Hey @brayanL,

We're looking into your issue and will get back to you soon.

**Comment by brayanL** [comment]
I don't think the project is badly linked, I checked all files on android Project and IOS project and seems all is fine. I would like to share the project so you could see the error but I'm working with react-native vanilla without expo.

**Comment by petradonka** [comment]
Hey @brayanL,

Our support team got in contact with you to further investigate the issues you're having and help you resolve them, so I'm going to close this as they took over.

Cheers,
Petra
