### ISSUE TITLE
BarcodePicker doesn't pick new camera permissions  

### ISSUE THREAD

**Issue by vadimb** [Scandit/barcodescanner-sdk-react-native#180]
In all code samples if the camera permission is denied it is advised to exit the app so if you enable/disable permissions it will pick them  up as its being recreated. 

In our scenario we can't exit the app so I'm wondering if there is any recipe for that? Now in our app if the user opens the app with permission off and it enables it from the Android permission dialog the SDK keeps saying "The Barcode Picker was unable to access the device camera..." but only that behind it we have the scanner active without the usual UI (2 screenshoot). Moreover it will work as in a normal mode(1 screenshoot).
It seems the SDK doesn't clear the missing camera overlay and it remains in a working state with wrong overlay.  
![Screenshot_3](https://user-images.githubusercontent.com/396352/66303058-d688b280-e902-11e9-89a7-d832942a4c15.png)
![Screenshot_1](https://user-images.githubusercontent.com/396352/66302853-624e0f00-e902-11e9-892c-35312aad9105.png)
![Screenshot_2](https://user-images.githubusercontent.com/396352/66302931-8c073600-e902-11e9-9377-28acafd80e47.png)

**Comment by petradonka** [comment]
Hey @vadimb,

Thanks for reaching out, we're going to look into the issue and get back to you.

— Petra

**Comment by TomekJurkowski** [comment]
Hey @vadimb,

it seems to me that you are calling `this.scanner.startScanning()` before you are actually sure that the permission has been granted. Our implementation of the `startScanning` method requires that the permission is already granted.

In your app, you can reuse our code for obtaining the camera permission and if you don't want the app to close, when the user denies the permission, just replace the logic of the `cameraPermissionDenied()` method with your own.

Let me know if that helps!

Cheers,
Tomek

**Comment by vadimb** [comment]
Hi @TomekJurkowski ,

Suppose we have permissions when calling startScanning for the first time. Now, if the user goes to to the app settings and switches off the permission then when we comeback to the app we'll have the 2 screenshoot. At this point we have 2 option either remove the BarcodePicker or call stop(which we do). We tried the first option but with no luck. After this if the user switches on the permissions  then you'll get 3 screenshoot that **actually work as the 1 first screen**  i.e its picks the new permissions and starts to scan just that the overlay isn't dropped. Is there way to reset or change the overlay?

**Comment by TomekJurkowski** [comment]
Hi @vadimb, thanks for the detailed description, now I have a much clearer picture of your issue. I will need to do some investigation regarding it tomorrow and will get back to you asap.

Cheers,
Tomek

**Comment by TomekJurkowski** [comment]
Hey @vadimb,

I played around with the camera permission just like you described using our SimpleSample (starting the app ---> granting it the permission ---> going to the app settings and revoking the permission ---> going back to the app) and I managed to tweak the sample so it checks again for the permission, never allowing you to start the barcode scanner without the camera permission. Here's a code snippet (we will also commit our changes to the repo, but since it might take a while, I don't want to block you):
```
import React, { Component } from 'react';
import {
  AppRegistry,
  AppState,
  StyleSheet,
  Text,
  findNodeHandle,
  View,
  Platform,
  PermissionsAndroid,
  BackHandler
} from 'react-native';
import {
  BarcodePicker,
  ScanditModule,
  ScanSession,
  Barcode,
  SymbologySettings,
  ScanSettings
} from 'scandit-react-native';

ScanditModule.setAppKey('-- ENTER YOUR SCANDIT LICENSE KEY HERE --');

export default class SimpleSample extends Component {

  componentWillMount() {
    this.settings = new ScanSettings();
    this.settings.setSymbologyEnabled(Barcode.Symbology.EAN13, true);
    this.settings.setSymbologyEnabled(Barcode.Symbology.EAN8, true);
    this.settings.setSymbologyEnabled(Barcode.Symbology.UPCA, true);
    this.settings.setSymbologyEnabled(Barcode.Symbology.UPCE, true);
    this.settings.setSymbologyEnabled(Barcode.Symbology.CODE39, true);
    this.settings.setSymbologyEnabled(Barcode.Symbology.ITF, true);
    this.settings.setSymbologyEnabled(Barcode.Symbology.QR, true);
    this.settings.setSymbologyEnabled(Barcode.Symbology.DATA_MATRIX, true);
    this.settings.setSymbologyEnabled(Barcode.Symbology.CODE128, true);

    /* Some 1d barcode symbologies allow you to encode variable-length data. By default, the
       Scandit BarcodeScanner SDK only scans barcodes in a certain length range. If your
       application requires scanning of one of these symbologies, and the length is falling
       outside the default range, you may need to adjust the "active symbol counts" for this
       symbology. This is shown in the following few lines of code. */
    this.settings.getSymbologySettings(Barcode.Symbology.CODE39)
      .activeSymbolCounts = [7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20];
    /* For details on defaults and how to calculate the symbol counts for each symbology, take
       a look at http://docs.scandit.com/stable/c_api/symbologies.html. */
  }

  isAndroidMarshmallowOrNewer() {
    return Platform.OS === 'android' && Platform.Version >= 23;
  }

  async hasCameraPermission() {
    if (this.isAndroidMarshmallowOrNewer()) {
      const granted = await PermissionsAndroid.check(PermissionsAndroid.PERMISSIONS.CAMERA);
      return granted;
    } else {
      return true;
    }
  }

  async requestCameraPermission() {
    if (this.isAndroidMarshmallowOrNewer()) {
      try {
        const granted = await PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.CAMERA);
        if (granted === PermissionsAndroid.RESULTS.GRANTED) {
          console.log("Android Camera Permission has been granted.");
          this.cameraPermissionGranted();
        } else {
          console.log("Android Camera Permission has been denied - the app will shut itself down.");
          this.cameraPermissionDenied();
        }
      } catch (err) {
        console.warn(err);
      }
    } else {
      this.cameraPermissionGranted();
    }
  }

  // This method should only be called if the Platform.OS is android.
  cameraPermissionDenied() {
    BackHandler.exitApp();
  }

  cameraPermissionGranted() {
    this.scanner.startScanning();
  }

  async componentDidMount() {
    AppState.addEventListener('change', this._handleAppStateChange);
    this.checkForCameraPermission();
  }
  
  componentWillUnmount() {
    AppState.removeEventListener('change', this._handleAppStateChange);
  }
  
  _handleAppStateChange = async (nextAppState) => {
    if (nextAppState.match(/inactive|background/)) {
      this.scanner.stopScanning();
    } else {
      this.checkForCameraPermission();
    }
  }

  async checkForCameraPermission() {
    const hasPermission = await this.hasCameraPermission();
    if (hasPermission) {
      this.cameraPermissionGranted();
    } else {
      await this.requestCameraPermission();
    }
  }

  render() {
    return (
      <View style={{
        flex: 1,
        flexDirection: 'column'}}>
        <BarcodePicker
          onScan={(session) => { this.onScan(session) }}
          scanSettings= { this.settings }
          ref={(scan) => { this.scanner = scan }}
          style={{ flex: 1 }}/>
      </View>
    );
  }

  onScan(session) {
    alert(session.newlyRecognizedCodes[0].data + " " + session.newlyRecognizedCodes[0].symbology);
  }

}
```

As you can see, I am taking the advantage of react native's AppState (https://facebook.github.io/react-native/docs/appstate.html)
to also check for camera permission whenever the app goes to `active` state.

This approach should help with your issue. If you need any further help, feel free to reach out!

Cheers,
Tomek

**Comment by vadimb** [comment]
@TomekJurkowski ,

I see that, but what should be the logic in the  `cameraPermissionDenied()`  in case we can't  exit the app? Do we call stop ?

Thanks,
Vadim

**Comment by TomekJurkowski** [comment]
@vadimb,

you should stop the scanner the moment you change the state to "background", by exiting the app and going to app settings. In such scenario, when you go back to your app (without the camera permission) and the `cameraPermissionDenied()` is called, you don't have to do anything with the scanner, because it is already stopped.

Cheers,
Tomek

**Comment by vadimb** [comment]
OK, now if you go again to settings(while the app is stop state) and enable camera you'll get the 3 screen - i.e you'll get stuck with overlay while the SDK is king working.

Thanks,
Vadim

**Comment by TomekJurkowski** [comment]
hmmm that I cannot reproduce. If you only start the scanner when you are sure you have the permission, then you won't ever get the overlay with the error message.

**Comment by vadimb** [comment]
I'll try modify one of the samples to reproduce that.

**Comment by TomekJurkowski** [comment]
Hey @vadimb ,
how you doin'? did you find a workaround for your problem or do you need some further assistance from us?

Cheers,
Tomek

**Comment by vadimb** [comment]
@TomekJurkowski ,

sorry for late response. I'll try it again and I'm planing to create a reproducible sample proj if I wont be able to get it working.
