### ISSUE TITLE
Update SimpleSample project samples folder.

### ISSUE THREAD

**Issue by brayanL** [Scandit/barcodescanner-sdk-react-native#192]
Hi Scandit is awesome is very faster.

The project does not run unless you do the following:

1. I'm was trying to use SimpleSample but I realize there are many codes lines missing. On that project, you are using react-native: 0.59.1, but if you look [react native upgrade helper](https://react-native-community.github.io/upgrade-helper/ ) you will be able to see the missing files and the code lines and packages that should be used with the specific version of react-native.

2. Metro Bundler crash with the following error reported on React Native: [Issue](https://github.com/facebook/react-native/issues/24112#issuecomment-475887150) 

Scandit is a payment library should not exist these problems.

Following the steps above I achieved the project works, the barcode app is awesome and faster....!

**Comment by petradonka** [comment]
Hi @brayanL,

We're glad you like the Scandit SDK and it's working out well for you!
Thanks for reporting these issues, we'll improve the samples in an upcoming release.

Cheers,
Petra
