### ISSUE TITLE
dotcode not scanning

### ISSUE THREAD

**Issue by musadiq-jinbade** [Scandit/barcodescanner-sdk-react-native#197]
While scanning dot code is not scanning a product of Marlboro product. small dot code is not scanning in scandit library

**Comment by lucatorella** [comment]
Hi @musadiq-jinbade, this is very unfortunate. Can you send an email to support@scandit.com and attach a picture of the code that is not working for you please? Thanks.

**Comment by musadiq-jinbade** [comment]
I going share image of dot code please look around
![IMG_20191202_162441](https://user-images.githubusercontent.com/54430156/69954661-d501f200-1521-11ea-8373-c88d1672c331.jpg)

**Comment by lucatorella** [comment]
I can scan this code in our app (did you try? You can find it in the App Store/Play Store). This means that our SDK should be able to scan it as well. Maybe it's a misconfiguration. Can you send us the code you are using?

**Comment by musadiq-jinbade** [comment]
I can scan the dot code if I generated only, but I can't scan on this product.

**Comment by musadiq-jinbade** [comment]
code:

this.settings = new ScanSettings();
        this.settings.setSymbologyEnabled(Barcode.Symbology.EAN13, true);
        this.settings.setSymbologyEnabled(Barcode.Symbology.DOTCODE, true);
        this.settings.setSymbologyEnabled(Barcode.Symbology.EAN8, true);
        this.settings.setSymbologyEnabled(Barcode.Symbology.UPCA, true);
        this.settings.setSymbologyEnabled(Barcode.Symbology.UPCE, true);
        this.settings.setSymbologyEnabled(Barcode.Symbology.CODE39, true);
        this.settings.setSymbologyEnabled(Barcode.Symbology.ITF, true);
        this.settings.setSymbologyEnabled(Barcode.Symbology.QR, true);
        this.settings.setSymbologyEnabled(Barcode.Symbology.DATA_MATRIX, true);
        this.settings.setSymbologyEnabled(Barcode.Symbology.CODE128, true);
        this.settings.getSymbologySettings(Barcode.Symbology.CODE39)
            .activeSymbolCounts = [7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20];
        this.settings.getSymbologySettings(Barcode.Symbology.DOTCODE)
        .activeSymbolCounts = [7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20];

**Comment by musadiq-jinbade** [comment]
barcode scanner


<BarcodePicker
                            onScan={(session) => { this.onScan(session) }}
                            scanSettings={this.settings}
                            ref={(scan) => { this.scanner = scan }}
                            style={{
                                flex: 1, height: this.state.model || this.state.delete ? this.state.Updatedata ?
                                    this.state.Updatedata === undefined ? null : hgt - widthPercentageToDP('103%') : hgt - widthPercentageToDP('45%') : hgt - widthPercentageToDP('22.1%')
                            }} />

**Comment by lucatorella** [comment]
Can you enable an higher resolution? `this.settings.highDensityModeEnabled = true;`

**Comment by musadiq-jinbade** [comment]
> this.settings.highDensityModeEnabled = true;

I have tried but not working, the camera is flicking, I think this is not working

**Comment by musadiq-jinbade** [comment]
can you suggest scan setting in barcode scanner

**Comment by lucatorella** [comment]
can you write support@scandit.com? They will be able to help you.

**Comment by musadiq-jinbade** [comment]
![Screenshot_20191202-183708](https://user-images.githubusercontent.com/54430156/69962233-9117e880-1533-11ea-82a4-ab7615d6e000.png)

**Comment by musadiq-jinbade** [comment]
> I can scan this code in our app (did you try? You can find it in the App Store/Play Store). This means that our SDK should be able to scan it as well. Maybe it's a misconfiguration. Can you send us the code you are using?

let me share my code with you

**Comment by musadiq-jinbade** [comment]
ScanditModule.setAppKey('-----scandit key----')


class LinkScanproduct extends Component {
    static navigationOptions = { header: null }
    constructor(props) {
        super(props);
        this.state = {
            selectedItems: [],......

       }
}
async componentWillMount() {
        this.settings = new ScanSettings();
        // this.settings.setSymbologyEnabled(Barcode.Symbology.EAN13, true);
        this.settings.setSymbologyEnabled(Barcode.Symbology.DOTCODE, true);
        // this.settings.setSymbologyEnabled(Barcode.Symbology.EAN8, true);
        // this.settings.setSymbologyEnabled(Barcode.Symbology.UPCA, true);
        // this.settings.setSymbologyEnabled(Barcode.Symbology.UPCE, true);
        // this.settings.setSymbologyEnabled(Barcode.Symbology.CODE39, true);
        // this.settings.setSymbologyEnabled(Barcode.Symbology.ITF, true);
        this.settings.setSymbologyEnabled(Barcode.Symbology.QR, true);
        // this.settings.setSymbologyEnabled(Barcode.Symbology.DATA_MATRIX, true);
        // this.settings.setSymbologyEnabled(Barcode.Symbology.CODE128, true);
        // this.settings.getSymbologySettings(Barcode.Symbology.CODE39)
        //     .activeSymbolCounts = [7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20];
        this.settings.getSymbologySettings(Barcode.Symbology.DOTCODE, true)
        .activeSymbolCounts = [7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20];
        
        this.settings.highDensityModeEnabled = true;
        this.settings.beep = true;
        this.settings.vibrate = true;
        // this.settings.getSymbologySettings = true;
    }

 isAndroidMarshmallowOrNewer() {
        return Platform.OS === 'android' && Platform.Version >= 23;
    }


    async hasCameraPermission() {
        if (this.isAndroidMarshmallowOrNewer()) {
            const granted = await PermissionsAndroid.check(PermissionsAndroid.PERMISSIONS.CAMERA);
            return granted;
        } else {
            return true;
        }
    }

    async requestCameraPermission() {
        if (this.isAndroidMarshmallowOrNewer()) {
            try {
                const granted = await PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.CAMERA);
                if (granted === PermissionsAndroid.RESULTS.GRANTED) {
                    console.log("Android Camera Permission has been granted.");
                    this.cameraPermissionGranted();
                } else {
                    console.log("Android Camera Permission has been denied - the app will shut itself down.");
                    this.cameraPermissionDenied();
                }
            } catch (err) {
                console.warn(err);
            }

        } else {

            this.cameraPermissionGranted();

        }

    }


    cameraPermissionDenied() {
        BackHandler.exitApp();
    }


    cameraPermissionGranted() {
        this.scanner.startScanning();
    }



    async componentDidMount() {

        AppState.addEventListener('change', this._handleAppStateChange);
        this.checkForCameraPermission();

        // console.log("prop data:", this.props.navigation.state.params.item)
        this.setState({ model: true, props: this.props.navigation.state.params.item }, () => {
            console.log("prop data:", this.state.props)

        });
    }


    componentWillUnmount() {
        AppState.removeEventListener('change', this._handleAppStateChange);
        if (this.timeout) {
             clearTimeout(this.timeout)
         }
    }



    _handleAppStateChange = async (nextAppState) => {
        if (nextAppState.match(/inactive|background/)) {
            this.scanner.stopScanning();
        } else {
            this.checkForCameraPermission();
        }

    }



    async checkForCameraPermission() {
        const hasPermission = await this.hasCameraPermission();
        if (hasPermission) {
            this.cameraPermissionGranted();
        } else {
            await this.requestCameraPermission();
        }
    }

render() {
        const { selectedItems, timePassed } = this.state
        const hgt = Dimensions.get("window").height

        const wdt = Dimensions.get("window").width

        console.log("height:", hgt - widthPercentageToDP('95%'));
        return (

<BarcodePicker
                            onScan={(session) => { this.onScan(session) }}
                            scanSettings={this.settings}
                            ref={(scan) => { this.scanner = scan }}
                            style={{
                                flex: 1, height: this.state.model || this.state.delete ? this.state.Updatedata ?
                                    this.state.Updatedata === undefined ? null : hgt - widthPercentageToDP('103%') : hgt - widthPercentageToDP('45%') : hgt - widthPercentageToDP('22.1%')
                            }} />

);
}

 onScan(session) {
        this.scanner.pauseScanning();.....
}

}

**Comment by musadiq-jinbade** [comment]
> I going share image of dot code please look around
> ![IMG_20191202_162441](https://user-images.githubusercontent.com/54430156/69954661-d501f200-1521-11ea-8373-c88d1672c331.jpg)



this dot code  will be scanning perfectly but while scanning small dot code in above Marlboro will not scan
 
![image](https://user-images.githubusercontent.com/54430156/70028264-37163200-15ca-11ea-9029-e1b21d26ff35.png)

**Comment by petradonka** [comment]
Hey @musadiq-jinbade,

Our support team will be able to help you much better with your issue, please write support@scandit.com so we can sort this out more efficiently.

Cheers,
Petra
