### ISSUE TITLE
camera flicking

### ISSUE THREAD

**Issue by musadiq-jinbade** [Scandit/barcodescanner-sdk-react-native#198]
while scanning dot code/ Qr code scandit camera is flicking in react native application,

**Comment by petradonka** [comment]
Hey @musadiq-jinbade,

This seems like an underlying camera issue that our support team needs to look at, please contact us through support@scandit.com with more details about the device and OS that you're using.

Cheers,
Petra

**Comment by musadiq-jinbade** [comment]
Thanks for updating quickly.

**Comment by musadiq-jinbade** [comment]
I can't able scan dot code on Marlboro box
![IMG_20191202_162441](https://user-images.githubusercontent.com/54430156/70301673-08de5f80-1821-11ea-9815-c56cb206e11e.jpg)
 but  I can scan after generating in dot code

**Comment by petradonka** [comment]
This seems to be a very different issue than the previous one, support@scandit.com will be able to help you with this as well.
