### ISSUE TITLE
Scandit Barcode Scanner won't scan/recognize Barcode symbology Code 39

### ISSUE THREAD

**Issue by jetonk** [Scandit/barcodescanner-sdk-react-native#200]
I'm using React Native latest version with ExpoKit36 and I generate barcodes from https://www.scandit.com/barcode-generator/ when I try to scan Code128 it works but Code39 it doesn't work.

I have enabled settings like this.
```
const settings = new ScanSettings();
settings.setSymbologyEnabled(Barcode.Symbology.CODE128, true);
settings.setSymbologyEnabled(Barcode.Symbology.CODE39, true);
```

**Comment by petradonka** [comment]
Hey @jetonk,

Are you able to scan the same codes with the Scandit Demo app for iOS or Android?
- iOS: https://itunes.apple.com/us/app/scandit-barcode-scanner-demo/id453880584?ls=1&mt=8
- Android: https://play.google.com/store/apps/details?id=com.scandit.demoapp

— Petra

**Comment by jetonk** [comment]
@petradonka Yes I just tried that and it worked. Using the section Any code

**Comment by petradonka** [comment]
Thanks for checking! Please reach out to support@scandit.com then, they can help you out with the issue and/or escalate it to the right place if necessary.

**Comment by jetonk** [comment]
@petradonka Issue was related to the license, we had to re-issue our license. I'm going to close this issue, thank you a lot.
