### ISSUE TITLE
Reinstall pods every time node_modules dependency is added

### ISSUE THREAD

**Issue by ruckk** [Scandit/barcodescanner-sdk-react-native#206]
Every time I add a dependency to with npm or yarn the node_modules/scandit-react-native/ios/ScanditBarcodeScanner/Frameworks is removed. So I have to create it and add ScanditBarcodeScanner.framework again, then reinstall all pods to make it work.

Is there some other way to deal with this?

**Comment by petradonka** [comment]
Hey @ruckk,

In this case, we'd suggest that you commit the framework to your repo in a folder other than `node_modules` and add a `postinstall` script to copy this to the appropriate folder (`node_modules/scandit-react-native/ios/ScanditBarcodeScanner/Frameworks`) every time you install a dependency.  If you want to learn more about the postinstall hook, take a look at https://docs.npmjs.com/misc/scripts.
You could potentially also automate any other necessary steps this way, e.g. reinstalling pods.

Hope this helps.

Cheers,
Petra

**Comment by ruckk** [comment]
Yea that's what I was thinking about doing. And if theres no other way I guess I'll do that. Thanks.
