### ISSUE TITLE
Will you be adding a typescript declaration file anytime soon?

### ISSUE THREAD

**Issue by maderesponsively** [Scandit/barcodescanner-sdk-react-native#207]
Will you be adding a typescript declaration file anytime soon?

**Comment by maderesponsively** [comment]
Will you be adding a typescript declaration file anytime soon?

**Comment by petradonka** [comment]
Hey @maderesponsively,

It's on our product roadmap, for further details you can contact support@scandit.com. They can give you more information.

Cheers,
Petra
