### ISSUE TITLE
Getting error in React Native version 0.61.5

### ISSUE THREAD

**Issue by karthinidc** [Scandit/barcodescanner-sdk-react-native#211]
Getting the below error in React Native 0.61.5 project

TypeError: Cannot read property 'setApiKey' of undefined

Using the latest version of Scandit-react-native

    "react": "16.9.0",
    "react-native": "0.61.5",

![Simulator Screen Shot - iPad Air (3rd generation) - 2020-03-26 at 13 47 04](https://user-images.githubusercontent.com/59463519/77871429-bad2e900-7261-11ea-9ad3-3103b282bed2.png)

**Comment by petradonka** [comment]
Hi @karthinidc,

It seems like the plugin isn't added or loaded properly. Are there any other errors while installing the plugin or running the app? You could take a look at our [Getting Started](https://docs.scandit.com/stable/react_native/react-native-integrate.html) guide to make sure all the necessary steps were done.
Additionally, you could also check if you are able to scan with one of our samples.

Cheers,
Petra

**Comment by karthinidc** [comment]
Hi @petradonka 

Not getting any error in the Installing but getting app in the running time. Below error


 TypeError: null is not an object (evaluating '_scanditReactNative.ScanditModule.setAppKey')
2020-03-30 13:04:08.148 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: TypeError: null is not an object (evaluating '_scanditReactNative.ScanditModule.setAppKey')

**Comment by petradonka** [comment]
Hi @karthinidc,

That error usually happens when the plugin isn't loaded properly for some reason. If there are no errors while installing and you can run our samples, I suggest that you reach out to support@scandit.com where we'll be able to help you troubleshoot this better.

Cheers,
Petra

**Comment by tamslinn** [comment]
@petradonka I was wondering how you resolved this? I have exactly the same problem despite following the install instructions carefully

**Comment by tamslinn** [comment]
@karthinidc I was wondering how you resolved this? I have exactly the same problem despite following the install instructions carefully. Thanks

**Comment by petradonka** [comment]
Hey @tamslinn,

If you're just getting started integrating our SDK, I suggest using the newer version for RN: https://docs.scandit.com/data-capture-sdk/react-native/index.html. The integration of the newer version is much easier.

The upcoming 5.19 release will be the last release for barcodescanner-sdk-react-native (this repo), we'll only be supporting the 6.x, Data Capture version I linked above going forward.

— Petra

**Comment by tamslinn** [comment]
@petradonka thanks for the info - we were just trying to upgrade from 5.11.3 to the latest version at this point as we already have existing code. It looks like migrating to the new SDK will require a bit more work, so we'll have to plan that in.

**Comment by petradonka** [comment]
@tamslinn, in that case, I think the best approach is to reach out to support@scandit.com, they should be able to help either with the upgrade or the migration.
