### ISSUE TITLE
Error while trying to run SimpleSample

### ISSUE THREAD

**Issue by aanklewicz92** [Scandit/barcodescanner-sdk-react-native#217]
I followed all the steps described here: [https://docs.scandit.com/stable/react_native/react-native-examples.html](https://docs.scandit.com/stable/react_native/react-native-examples.html). When I run `react-native run-android`, project builds, Metro server starts, but when app opens on device I get an error:

`Unable to load script. Make sure you're either running a Metro server (run 'react-native start') or that your bundle 'index.android.bundle' is packaged correctly for release.`

![image](https://user-images.githubusercontent.com/11396814/81898747-9afd4780-95b9-11ea-89a9-4f25a6a84071.png)

**Comment by petradonka** [comment]
Hi @aanklewicz92,

It looks like the JS bundle can not be loaded. You mentioned that the Metro server starts, can you see any errors there? Do you see the app attempting to connect, but maybe failing?

Could you also provide us with some more info around your setup? Such as OS version, Scandit React Native version, platform, development platform, and anything else you might think is relevant.

Thanks,
— Petra

**Comment by aanklewicz92** [comment]
Hello @petradonka 

Thank you for such a quick answer. Here's some setup info:

- Trying to run app on device running  Android 9 (but I also want to make it work on iOS once Android works),
- React Native Cli version: 2.0.1,
- Yarn version: 1.22.4,
- Working on Windows 10,
- I didn't change `package.json`, so everything there is like on repo:
```
{
"name": "SimpleSample",
  "version": "5.15.0",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "preinstall": "../sample_install.sh",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {
    "prop-types": "15.6.2",
    "react": "16.8.3",
    "react-native": "0.59.10",
    "scandit-react-native": "file:../../"
  },
  "devDependencies": {
    "@babel/core": "^7.4.4",
    "metro": "^0.45.6",
    "metro-core": "^0.45.6",
    "metro-react-native-babel-preset": "^0.54.0",
    "react-test-renderer": "16.8.3"
  }
}
```

I don't see any errors in Metro server nor in PowerShell where I run the `react-native run-android`. To be honest, there is not too much there. Metro server says it looks for JS files, then says graph is loaded, while PowerShell after successful build runs adb and starts an Intent. So the only info about error I have on the device screen.

**Comment by petradonka** [comment]
Hi @aanklewicz92:

Without a clear error, we'll need more info to look into this and eliminate potential causes. Please reach out to support@scandit.com with the info above. They are more versed in these issues and will be able to help you sort this out more effectively.

Cheers,
— Petra
