### ISSUE TITLE
Execution failed for task ':app:mergeDebugResources'.

### ISSUE THREAD

**Issue by eFabrica** [Scandit/barcodescanner-sdk-react-native#222]
I add files *.aar in  myProject\android\lib - but error show ->

> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find :ScanditBarcodeScanner:.
     Searched in the following locations:
       - file:/C:/Users/efabrica/Downloads/barcodescanner-sdk-react-native-release-5.15/barcodescanner-sdk-react-native-release-5.15/samples/SimpleSample/android/libs/ScanditBarcodeScanner.aar
     Required by:
         project :app > project :scandit-react-native

**Comment by petradonka** [comment]
Hi @eFabrica,

You mentioned that you added the *.aar files under "myProject\android\lib", but we expect them under "myProject\android\libs", also as shown in the error message. Could the problem be just a typo? If you're still having issues, please reach out to support@scandit.com, our support team will be happy to help you sort this out.

Cheers,
— Petra

**Comment by eFabrica** [comment]
I'm sorry, I entered "lib" but I had actually put "libs" - The error is correct. I don't have this "ScanditBarcodeScanner.aar" file, where can I download it?


----- LIBS FOLDER CONTENT

                                                                              
     Directory: C: \ Sistemasagv \ develop \ app-rf \ packages \ mobile \ android \ libs
                                                                              
                                                                              
Mode LastWriteTime Length Name
---- ------------- ------ ----
-a ---- 22/05/2020 13:41 1220400 ScanditBarcodeCapture.aar
-a ---- 22/05/2020 13:41 16895855 ScanditCaptureCore.aar
-a ---- 22/05/2020 13:41 255341 ScanditParser.aar

**Comment by petradonka** [comment]
You'll need to download it from the Scandit dashboard, https://ssl.scandit.com/sdk. You'll also have to make sure that you're downloading the same version of the native (Android, iOS) libraries that you're using for React Native. Based on the error message from before, that'd be 5.15.

**Comment by eFabrica** [comment]
kkkkk I'm sorry, just now I found it. Thank you.
