### ISSUE TITLE
feat: add blur outside activeScanningAreaPortrait

### ISSUE THREAD

**Issue by troZee** [Scandit/barcodescanner-sdk-react-native#223]
Hey, 
I would like to have blur overlay outside the activeScanningAreaPortrait. I could not find it in docs https://docs.scandit.com/stable/react_native/class_scandit_1_1_scan_overlay.html 

I would like to ask, if there is any plan to support this kind of functionality ?

**Comment by petradonka** [comment]
Hi @troZee,

We currently don't have this feature. In our upcoming 6.x version of our React Native plugin, you'll find new ways to visualize scanning, it's expected to be out this quarter. If you'd like to get more info about the new features, please reach out to support@scandit.com, they'll be able to tell you more about our product roadmap.

Cheers,
Petra
