### ISSUE TITLE
ScanditDataCaptureCore is unavailable: cannot find Swift declaration for this class

### ISSUE THREAD

**Issue by candemore1024** [Scandit/barcodescanner-sdk-react-native#230]
### Problem

Using the sample “BarcodeCaptureSimpleSample” (SDK version 6.5.2), the build with Xcode is failing with the error:

/BarcodeCaptureSimpleSample/node_modules/scandit-react-native-datacapture-barcode/ios/Sources/BarcodeTracking/ScanditDataCaptureBarcodeTracking+Deserializer.swift:16:9: 'ScanditDataCaptureCore' is unavailable: cannot find Swift declaration for this class

/ScanditDataCaptureCore.ScanditDataCaptureCore:2:12: 'ScanditDataCaptureCore' has been explicitly marked unavailable here

### Steps to reproduce

- Download zip (SDK version 6.5.2) from https://ssl.scandit.com/sdk
- yarn install
- cd ios && pod install
- Xcode -> Build with a physical device (iPhone 6 plus - iOS 12.4)
- Xcode -> Clean Build Folder
- Xcode -> Build with a physical device (iPhone XS Max - iOS 14.0)
- Xcode -> Clean Build Folder
- Xcode -> Build with “Generic iOS device”

### Environment

- react-native-cli: 2.0.1 / react-native: 0.63.2
- Xcode 11.3.1
- MacOS 10.14.6

**Comment by ScanditSupport** [comment]
Hi @candemore1024 

Thanks for reaching out. 
The Scandit Support team is happy to help you. Please reach out via the official support channel 
https://support.scandit.com/hc/en-us/requests/new

Thank you. 
Your Scandit Support
