### ISSUE TITLE
ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by hanssl** [Scandit/barcodescanner-sdk-react-native#232]
I would like to test Scandit but I am getting an error when I try to import scant-sdk.

`import { useRouter } from 'next/router'
import { ScanSettings, Barcode } from "scandit-sdk";

import MemberLayout from '../../layouts/Member'

export default function BarcodeDemo(props) {

    const router = useRouter()

    return (
        <MemberLayout pageTitle="Items">
            Barcode
            <div id="demo" ></div>
            <div id="scandit-barcode-result" className="result-text"></div>
        </MemberLayout >
    )
}
`

<img width="1186" alt="Screen Shot 2020-12-19 at 3 49 28 AM" src="https://user-images.githubusercontent.com/649957/102687565-3b00fc00-41ad-11eb-8a4f-62304daa4e09.png">

**Comment by ScanditSupport** [comment]
Hi @hanssl 

thanks for reaching out. 
As you have recently opened another request regarding the WebSDK for react, you may want to reach out to us via https://support.scandit.com/hc/en-us/requests/new and a quick description of what you want to achieve such that we can comprehensively support you in using Scandit technology.

Best regards
Scandit Support

**Comment by hanssl** [comment]
I have tried several different ways to test your scanning library.  I have not been able to make any of them work.

**Comment by petradonka** [comment]
Hey @hanssl:

This repo contains the older, soon to be deprecated, version of our React Native SDK. Take a look at the docs for the improved 6.x version of our React Native plugin, including improved docs to get started: https://docs.scandit.com/data-capture-sdk/react-native/index.html

Cheers,
— Petra

**Comment by senorscan** [comment]
@hanssl or anyone else that lands on this and using Scandit in NextJS. You need to run as a dynamic component

e.g.
```js
const ScanditBarcodeScanner = dynamic(() => import('../components/Scandit'), { ssr: false });
```

Code mirror seem to have the same problem - https://dev.to/glowtoad123/using-codemirror-in-nextjs-without-the-navigator-error-opi

**Comment by ScanditSupport** [comment]
Hi @senorscan,

My apologies, as mentioned by @petradonka - ScanditBarcodeScanner is the deprecated version of our SDK.
Could you please migrate to the contemporary ScanditDataCapture SDK?
https://docs.scandit.com/data-capture-sdk/react-native/migrate-to-6.html 

In case you have more detailed questions, please feel free to reach out to us directly: [Submit a request – Frequently Asked Questions (FAQ)](https://support.scandit.com/hc/en-us/requests/new)
