### ISSUE TITLE
scandit sdk npm package

### ISSUE THREAD

**Issue by maapteh** [Scandit/barcodescanner-sdk-react-native#235]
Hi we where using 5.5.1 version of `scandit-sdk` package which got whiped from npm?

https://registry.yarnpkg.com/scandit-sdk/-/scandit-sdk-5.5.1.tgz

Then tried to install the 7 hours old version 5.5.2 which has a magic husky postinstall phase and fails?

_**Its weird i cant find the repo of scandit-sdk so dumping the issue here :)**_

```
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/scandit-sdk/-/scandit-sdk-5.5.1.tgz: Request failed \"404 Not Found\"".
```

error of your latest version 5.5.2 is:

```
error /Users/mpth/Git/SNIP/node_modules/scandit-sdk: Command failed.
Exit code: 127
Command: husky install
Arguments: 
Directory: /Users/mpth/Git/SNIP/node_modules/scandit-sdk
Output:
/bin/sh: husky: command not found
```

**Comment by ScanditSupport** [comment]
@maapteh 
Thanks for reaching out. 

We've released version 5.5.3 which fixes the npm script setup and this should solve the issue with the husky phase.

In case you have further questions, you can also reach out to us directly via 
https://support.scandit.com/
