### ISSUE TITLE
Failed to scan DIRECT_PART_MARKING_MODE with Data Matrix Extension

### ISSUE THREAD

**Issue by TommyLeong** [Scandit/barcodescanner-sdk-react-native#236]
We are trying to scan some DPM code with the following version in React Native app, realizing it didn't work as expected even if we have the extension pushed as such.

```
this.settings = new ScanSettings();
this.settings?.symbologies[Barcode.Symbology.DATA_MATRIX].extensions.push(SymbologySettings.Extension.DIRECT_PART_MARKING_MODE);
```

**Environment**
Package.json
```
"scandit-react-native": "^5.16.0",
"scandit-sdk": "^4.6.0",
```

npm info
```
 react: 16.13.1 => 16.13.1 
 react-native: 0.63.2 => 0.63.2 
```

**What I've tried**
1. Although the versioning user here is pretty old compare to the current available scandit-sdk version (5.6.0), I have tried upgrading the `scandit-sdk` to `5.6.0` still it doesn't recognize the DPM code. 

**Side ques:** 
1. What's the difference between scandit-sdk and scandit-react-native?
2. Do we need to match versioning between them? If yes, is there a table to refer to? 
Example, 
`scandit-sdk version 4` match with `scandit-RN 5`
`scandit-sdk version 5` match with `scandit-RN 6`
etc..
3. Am I right to say Scandit SDK Version 6 no longer require the current dependencies, instead it requires the following which stated in the documentation?
```
yarn add scandit-react-native-datacapture-core
yarn add scandit-react-native-datacapture-barcode
```

**Comment by ScanditSupport** [comment]
@TommyLeong as it sounds to be an individual issue, would you mind reaching out to us directly via support.scandit.com and provide an image of the dpm code?
We're happy to help you to update to the latest version of our SDK and adjust the required settings. 

Best regards
Scandit Support

**Comment by TommyLeong** [comment]
FYI, email has been sent.
