### ISSUE TITLE
Scandit License

### ISSUE THREAD

**Issue by chukiatt** [Scandit/barcodescanner-sdk-react-native#239]
Dear sir,

I would like to ask about scandit library for react native 
This library it can be used for free or have to buy a license?

thank you very much.

**Comment by ScanditSupport** [comment]
Hi @chukiatt,

Our library for React Native requires a license to be used. If you want to test it you can create a trial account on our website:  https://www.scandit.com/products/barcode-scanner-sdk/ (please click on the "Test SDK" button at the top of the page and fill the form).

In case you have more detailed questions, please feel free to reach out to us directly: 
https://support.scandit.com/hc/en-us/requests/new

Best regards

Scandit Support Team

**Comment by chukiatt** [comment]
Thank you very much
