### ISSUE TITLE
Torch Doesn't Work Despite Setting setTorchEnabled(true)

### ISSUE THREAD

**Issue by bryandent** [Scandit/barcodescanner-sdk-react-native#29]
Using the latest code base, Samples/SimpleSample project in this repo and .aar file from the Scandit online console, the setTorchEnabled function does not appear to work or is not honored. 

Code being used:
`
  componentDidMount() {
    this.scanner.setTorchEnabled(true);
    this.scanner.startScanning();
  }
`

Upon doing this, the view finder shows as follows:

![screenshot_20171130-091122](https://user-images.githubusercontent.com/1007794/33434944-d9ea4d30-d5ae-11e7-800e-1c889fef63cf.png)

**Comment by robertnawrot** [comment]
Hello, this will be fixed in the upcoming 5.6 release.
For now if you need the torch button visible, just don't call the `setTorchEnabled` function at all.

**Comment by swenner** [comment]
5.6.0BETA1 has been released (branched). Please try it and reopen this ticket if there is still an issue.
