### ISSUE TITLE
setOverlayProperty is not done on iOS

### ISSUE THREAD

**Issue by turnrye** [Scandit/barcodescanner-sdk-react-native#37]
setOverlayProperty is "todo" for iOS. 
https://github.com/Scandit/barcodescanner-sdk-react-native/blob/2bad971139f5d303fd46e4c45396619dc1af69bb/ios/ScanditBarcodeScanner/SCNBarcodePickerManager.m#L295

Would love for this to be implemented.

**Comment by katherinetucker** [comment]
setOverlayProperty is working for Android, but looks to not be implemented for iOS.  Is there a workaround to use while this is being worked on?

**Comment by moritz-scandit** [comment]
There is no actual setProperty function on the iOS native side (it is handled through private interfaces), that's the reason for it being missing here as well. What functionality are you looking for that is inside setOverlayProperty?

**Comment by katherinetucker** [comment]
Thank you for your response @moritz-scandit! We are trying to access the drawLogo property.  My team was previously advised to add -(void)drawLogo:(BOOL)draw; to SBSOverlayController.h when we were implementing the old SDK.  How should we access it with the react-native library?

**Comment by moritz-scandit** [comment]
As the functionality is a hidden property and not made public on purpose I took the liberty to censor your comment, sorry about that.
Currently if you need to do this on iOS you will need to adjust the native part of the plugin to get access to the private function. If it should be unclear how, then please write to us at support@scandit.com.
I will see that we discuss this issue that affects react native and cordova asap and hopefully provide a solution for it with the next release.

**Comment by moritz-scandit** [comment]
I just realized it's not that easy to adjust the native part as your project will depend on this repository. So currently you won't be able to do anything probably other than having a private fork of this repo and changing it there.
I will update this ticket by tomorrow evening about further decisions in how we approach it. My apologies for the inconvenience.

**Comment by moritz-scandit** [comment]
We decided to add the property in the same way as on Android ASAP as it is actually already available natively in a reduced state (compared to android). It should be available in the next few days and will work for your use case.

**Comment by turnrye** [comment]
Thanks @moritz-scandit!

**Comment by moritzhartmeier** [comment]
The function has been added to master and cherry picked back into 5.6 for production use.
