### ISSUE TITLE
Scanner crashes for iOS versions < 9.0

### ISSUE THREAD

**Issue by katherinetucker** [Scandit/barcodescanner-sdk-react-native#42]
For release-5.6, iOS crashes for versions < 9.0.  The issue is with the SCNBarcodePicker.m on line 122. 

This is the error:
<img width="845" alt="error" src="https://user-images.githubusercontent.com/25090890/35824105-60d3db16-0a77-11e8-994f-bc7c91975334.png">

It works if you replace -
strongSelf.onSettingsApplied(@{}); 

with something like -
NSDictionary *settings = [[NSDictionary alloc] init];
strongSelf.onSettingsApplied(settings);

**Comment by moritzhartmeier** [comment]
Thanks for the report, we will address this asap.

**Comment by lucatorella** [comment]
Weird, looks like a compiler issue. Anyway, `strongSelf.onSettingsApplied(nil);`might also work. Let's check.
