### ISSUE TITLE
Error 6: Connect your device to the network and restart the application. Network is mandatory for the Test license.

### ISSUE THREAD

**Issue by JorgeCeja** [Scandit/barcodescanner-sdk-react-native#49]
I am getting this error on both ios and android. 

I have also done the steps mentioned [here](https://support.scandit.com/hc/en-us/articles/208232445-License-Errors) to solve the problem

react native - 0.48.4

**Comment by lucatorella** [comment]
Hi @JorgeCeja, are you maybe behind a firewall? If that's not the case, can you write support so that we can check your account?
