### ISSUE TITLE
Scan don't work on Android

### ISSUE THREAD

**Issue by brunoksato** [Scandit/barcodescanner-sdk-react-native#6]
My app works fine on IOS, but android open Camera but not match the scan.

Maybe I did something wrong? 

Example my code: https://gist.github.com/brunoksato/a630118a243c346129feb76bad73154d

```
"dependencies": {
    "lodash": "^4.17.4",
    "native-base": "^2.3.1",
    "react": "^16.0.0-alpha.12",
    "react-native": "^0.47.2",
    "react-native-aws3": "0.0.8",
    "react-native-camera": "^0.10.0",
    "react-native-scandit": "git+https://github.com/Scandit/barcodescanner-sdk-react-native.git",
    "react-native-simple-store": "^1.3.0",
    "react-native-vector-icons": "^4.3.0",
    "react-navigation": "1.0.0-beta.12"
  }

**Comment by brunoksato** [comment]
anyone ?

**Comment by robertnawrot** [comment]
Can you provide information about the device and android version?
Also, I'd like to just confirm that you are seeing the camera preview with the Scandit logo, but no codes are being recognized, is that correct?
What type of codes are you trying to scan? Are their symbologies enabled and the symbol counts match?

**Comment by brunoksato** [comment]
@robertnawrot 
Device list: 
Lenovo
Motorola G
Motorola X
Samsung Galaxy s6
Samsung Galaxy s7

Android version 5,6,7

Yes, I see camera preview with Scandit logo and codes not being recognized.

type of codes used and these symbologies are active too: 
'EAN13'
'EAN8'
'UPCE'

After seeing this plugin don't work I back to use this https://github.com/salathegroup/react-native-scandit with the same cases and works fine.

**Comment by moritz-scandit** [comment]
We do not see any issues with those symbologies in our tests, can you provide us the code for initializing the picker that you used?

**Comment by brunoksato** [comment]
hi @moritz-scandit

I found the problem happens when trying use ```async in componentWillMount``` so Symbology not works

```
async componentWillMount() {
    this.settings = new ScanSettings();
    this.settings.setSymbologyEnabled(Barcode.Symbology.EAN13, true);
    this.settings.setSymbologyEnabled(Barcode.Symbology.EAN8, true);
    this.settings.setSymbologyEnabled(Barcode.Symbology.UPCA, true);
    this.settings.setSymbologyEnabled(Barcode.Symbology.UPCE, true);
    this.settings.setSymbologyEnabled(Barcode.Symbology.CODE39, true);
    this.settings.setSymbologyEnabled(Barcode.Symbology.CODE128, true);
    this.settings.getSymbologySettings(Barcode.Symbology.CODE39)
      .activeSymbolCounts = [7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20];
  }
```

**Comment by brunoksato** [comment]
I will wait for good support for it, this causes others big bugs in my application.

**Comment by robertnawrot** [comment]
@brunoksato 
I copied your `async componentWillMount()` function and it still worked in our sample.
If you'd like me to investigate more I would need a version of your code that I could run.

**Comment by diegoddox** [comment]
I'm facing the same issue with the android device, the scanner just stopped working with the QR code and some others as well.

**Comment by robertnawrot** [comment]
Hello @diegoddox 
I am still not able to reproduce the issues you are reporting. Are you able to reproduce this behaviour with one of our sample apps? If not, can you provide a minimum code sample that allows me to reproduce the issue? Any other additional info would be greatly appreciated. 
Cheers

**Comment by diegoddox** [comment]
@robertnawrot the error is gone!

**Comment by lucatorella** [comment]
Do you know how? 🙂
