### ISSUE TITLE
Go back previous screen freezes scanner

### ISSUE THREAD

**Issue by boris-graeff** [Scandit/barcodescanner-sdk-react-native#92]
Hi, I got a weird behavior on go back navigation (with react-navigation).

I have two screens A and B which both have BarcodePicker component inside.
If navigate from A to B, then go back to A scanner is like freezed.

If I remove BarcodePicker from screen B then it works as expected: when I go back on screen A scanner is reactive.

Did I miss something ?

Thanks

**Comment by fatalaa** [comment]
Hi,
Thank you for your interest in our SDK.

Do you mind sharing some details, like platform, SDK version. Also, some code would be helpful for us before we move further with this.

**Comment by boris-graeff** [comment]
Sure,

- scandit-react-native: 5.8.2
- SDK android: 5.8.2
- Android device: 6.0.1

Screen A
```
import { BarcodePicker, ScanSettings } from 'scandit-react-native';
import React from 'react';
import { View } from 'react-native';

export default class TestA extends React.Component {

    constructor(props) {
        super(props);

        this.settings = new ScanSettings();
        this.settings.codeDuplicateFilter = 3000;
        this.settings.setSymbologyEnabled('qr', true);
    }

    handleScan(scan) {
        this.props.navigation.navigate('TestB');
    }

    componentDidMount() {
        this.scanner.startScanning();
    }

    render() {
        return (
            <View style={{ flex: 1 }}>
                <BarcodePicker
                    style={{ flex: 1 }}
                    ref={(scan) => {
                        this.scanner = scan;
                    }}
                    scanSettings={this.settings}
                    onScan={(session) => this.handleScan(session)}
                />
            </View>
        );
    }
}

```

Screen B
```
import { BarcodePicker, ScanSettings } from 'scandit-react-native';
import React from 'react';
import { View } from 'react-native';

export default class TestA extends React.Component {

    constructor(props) {
        super(props);

        this.settings = new ScanSettings();
        this.settings.codeDuplicateFilter = 3000;
        this.settings.setSymbologyEnabled('qr', true);
    }

    handleScan(scan) {
        console.log(scan);
    }

    componentDidMount() {
        this.scanner.startScanning();
    }

    render() {
        return (
            <View style={{ flex: 1 }}>
                <BarcodePicker
                    style={{ flex: 1 }}
                    ref={(scan) => {
                        this.scanner = scan;
                    }}
                    scanSettings={this.settings}
                    onScan={(session) => this.handleScan(session)}
                />
            </View>
        );
    }
}
```

**Comment by boris-graeff** [comment]
Main
```
import React from 'react';
import { createSwitchNavigator, createStackNavigator } from 'react-navigation';
import { ScanditModule } from 'scandit-react-native';
import { Provider } from 'react-redux';
import config from 'react-native-config';
import AuthLoading from './Screens/AuthLoading';
import TestA from './Screens/Test/TestA';
import TestB from './Screens/Test/TestB';
import Login from './Screens/Login/Login';
import store from './store';

const { SCANDIT_TOKEN } = config;
ScanditModule.setAppKey(SCANDIT_TOKEN);

const AppStack = createStackNavigator(
    {
        TestA,
        TestB
    },
    {
        headerMode: 'none'
    }
);

const AuthStack = createStackNavigator(
    {
        Login
    },
    {
        headerMode: 'none'
    }
);


const Router = createSwitchNavigator(
    {
        AuthLoading,
        App: AppStack,
        Auth: AuthStack
    },
    {
        initialRouteName: 'AuthLoading'
    }
);

export default class App extends React.Component {

    render() {
        return (
            <Provider store={store}>
                <Router />
            </Provider>
        );
    }
}

```

**Comment by moritzhartmeier** [comment]
Thanks, we will have a look at this beginning of next wekk.

**Comment by TomekJurkowski** [comment]
Hi @boris-graeff , I started to look into the issue that you described and even though I haven't been able to reproduce your problem yet, from the code snippets that you provided I think I know what is causing the annoying `freeze`.

This might not be properly documented in our documentation yet - sorry about that, we'll fix that soon -  but having multiple BarcodePickers in the scanning state ( after the `startScanning()` method is called) can cause deadlocks. To avoid this issue, you should stop the BarcodePicker before you go from Screen A to Screen B and vice versa. You can most probably do it in the `componentWillUnmount()` method.

Please let us know if this helps. If you still are experiencing problems, even after you stop the picker in Screen A, before switching to Screen B) we will try to investigate it further.

Cheers

**Comment by boris-graeff** [comment]
Hi @TomekJurkowski , thanks for your help.

I use stack navigator so componentWillUnmount is not called when I navigate from A to B so it doesn't work.

But I'm gonna take a look to react navigation hooks https://reactnavigation.org/docs/en/navigation-prop.html#addlistener-subscribe-to-updates-to-navigation-lifecycle

**Comment by alexlevy0** [comment]
Same issue, its very annoying ! @TomekJurkowski @moritzhartmeier @fatalaa

**Comment by gitVera** [comment]
@boris-graeff did you solve the issue? I have the same problem

**Comment by ScanditSupport** [comment]
Hi @gitVera,

Please note that this thread is referring to a deprecated 5.x ScanditBarcodeScanner package.
The contemporary SDK is 6.x ScanditDataCapture:
https://docs.scandit.com/data-capture-sdk/react-native/index.html

Can you please reach out to us directly and share a few snippets of your code on how you implemented Scandit and specify the SDK version used?
[Submit a request – Frequently Asked Questions (FAQ) ](https://support.scandit.com/hc/en-us/requests/new)
